# name your datacenter
global:
  name: consul
  datacenter: kubernetes
  metrics:
    enabled: true

prometheus:
  enabled: true

server:
  replicas: 1

client:
  enabled: true

connectInject:
  enabled: true

ui:
  enabled: true

controller:
  enabled: true