# name your datacenter
global:
  name: consul
  datacenter: kubernetes
  metrics:
    enabled: true

prometheus:
  enabled: true

server:
  # use 1 server
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0

client:
  enabled: true
  grpc: true

connectInject:
  enabled: true

ui:
  enabled: true

controller:
  enabled: true